project_name: deepfake_watermark
epochs: 100
batch_size: 1
lr: 5e-4
image_size: 128
message_length: 30
message_range: 1
wm_factor: 0.03
device: "cuda:0"
lpips_w: 1
encoder_w: 15
all_w: 1
gnn: 0.01
df_w: 0.1
common_w: 3
dataset_path: /root/autodl-tmp/CelebAMask-HQ/vis
saved_images_number: 4
wm_channels: 4