project_name: deepfake_watermark
epochs: 100
batch_size: 32
lr: 5e-4
image_size: 256
message_length: 128
message_range: 1
wm_factor: 0.03
device: "cuda:0"
lpips_w: 1
encoder_w: 15
all_w: 1
gnn: 0.01
# df_w: 0.1
common_w: 3
dataset_path: /root/autodl-tmp/CelebAMask-HQ/train
saved_images_number: 4
wm_channels: 4
# info: "InstanceNorm2d, /root/autodl-tmp/code_bk/exp_highpass/2025.02.06-18.23.19/model_state_5.pth"